name: Helm Publish

on:
  push:
    branches: [ chehelm ] 

    # paths-ignore:
    #   - README.md
jobs:
  publish-helmchart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Configure git repo 
    #   run: |
    #      git config user.email "${{ secrets.EMAIL }}"
    #      git config user.name "${{ secrets.USER }}"     
    # - name: Create empty aws-gh-pages branch
    #   run: | 
    #        git switch --orphan my-gh-pages
    #        git commit --allow-empty -m "Initial commit"
    #        git push -u origin my-gh-pages
    - name: Create charts directory
      run: |
        pwd
        mkdir charts
        ls
    - name: copy helm-charts to charts folder
      run: |
        cp -a $GITHUB_WORKSPACE/democharts/*.tgz  $GITHUB_WORKSPACE/charts 
        cp -a $GITHUB_WORKSPACE/democharts/README.md  $GITHUB_WORKSPACE/charts    

    - name: Create index file
      run: helm repo index $GITHUB_WORKSPACE/charts  

    - name: check content of charts
      run: |
       cd charts
       ls
    - name: Create a mywebapp forlder in charts
      run: |
       cd $GITHUB_WORKSPACE/charts
       mkdir mychart
       
    - name: Move files from charts to mycharts
      run: |
        mv    $GITHUB_WORKSPACE/charts/*.tgz $GITHUB_WORKSPACE/charts/mychart

        mv $GITHUB_WORKSPACE/charts/index.yaml $GITHUB_WORKSPACE/charts/mychart
    # - name: Publish on GitHub Pages
    #   uses: ftnext/action-push-ghpages@v1.0.0
    #   with:
    #    build_dir: charts
    #    github_token: ${{ secrets.PATOKEN}}     
    #        mv $GITHUB_WORKSPACE/charts/README.md $GITHUB_WORKSPACE/charts/mycharts  

    - name: Publish on Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages2
        folder: charts
